version: '3'

volumes:
  jenkins_home:
    external: true
  nzbget_config:
    external: true
  radarr_config:
    external: true
  sonarr_config:
    external: true
  jackett_config:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    ports:
      - "8989:8989"
    volumes:
      - sonarr_config:/config
      - /volume1/media/tv:/tv
      - /volume1/downloads:/downloads
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    ports:
      - "7878:7878"
    volumes:
      - radarr_config:/config
      - /volume1/media/movies:/movies
      - /volume1/downloads:/downloads
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    ports:
      - 6789:6789
    volumes:
      - nzbget_config:/config
      - /volume1/downloads:/downloads
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
      - VERSION=public
    volumes:
      - /volume1/containers/plex:/config
      - /volume1/media/movies:/data/movies
      - /volume1/media/tv:/data/tvshows
    network_mode: host
    restart: unless-stopped
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    volumes:
      - jackett_config:/config
      # - <path to blackhole>:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
