version: '3'

volumes:
  nzbget_config:
    external: true

services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    ports:
      - "8989:8989"
    restart: unless-stopped
    volumes:
      - /volume1/containers/sonarr/config:/config
      - /volume1/media/tv:/tv
      - /volume1/downloads:/downloads
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /volume1/containers/radarr/config:/config
      - /volume1/media/movies:/movies
      - /volume1/downloads:/downloads
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
    restart: unless-stopped
    ports:
      - 6789:6789
    volumes:
      - nzbget_config:/config
      - /volume1/downloads:/downloads
  plex:
    image: linuxserver/plex
    container_name: plex
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Sydney
      - VERSION=public
    restart: unless-stopped
    volumes:
      - /volume1/containers/plex:/config
      - /volume1/media/movies:/data/movies
      - /volume1/media/tv:/data/tvshows
    network_mode: host
